# Generated by Django 4.1.1 on 2022-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmanagement', '0002_blog_blog_slug_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='max_length=50')),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
